---
title: "Untitled"
author: "Aaron Wolf"
date: "9/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(tidyr)
library(scales)
library(grid)
library(gridExtra)
library(stringr)
library(Metrics)
```


```{r}

Prop_blw_thrhld.fn <- function(callset, sample_size, min_window, quer_prop){
  dt.prop_blw_thrhld <- data.table()
  # Calculate the Pct_Int_Thrhld as the 99th percentile avg_pct_int for 8Mb window files
  dir <- '~/DATALab/NeanderthalSeq/IBDmix/desert_test/RealData/'
  callset <- callset #'callset_ALL.neand_ambig'
  sample_size <- sample_size #3046
  
  #pct_int_thrhld <- 0.0007762471

  pct_int_tbl <- fread(input = paste0(dir,'/',callset,'/','windows.8MB.100kb.bed.introgressed_bases_',quer_prop),
                                        header=FALSE,
                                        col.names = c('chr','strt','end','drop','quer','intr_bp')) %>%
                                  filter(!(chr %in% c('chrY','chrX','chrM'))) %>% filter(quer/(end-strt)>=quer_prop) %>%
                  mutate(pct_int = intr_bp/quer/sample_size)
  pct_int_thrhld <- pct_int_tbl$pct_int %>% quantile(probs=c(0.01)) %>% as.numeric() %>% log10()
  pct_int_thrhld <- 10 ^ round(pct_int_thrhld,digits = 2)
  
      
  for(winsize in seq(from=min_window, to = 15, by = 1)){  
    winsize <- winsize
    
    
    infile <- paste0(dir,'/',callset,'/', 'windows.',winsize,'MB.100kb.bed.introgressed_bases_',quer_prop)
    
    windows.introgressed_bases <- fread(input = infile,
                                        header=FALSE,
                                        col.names = c('chr','strt','end','drop','quer','intr_bp')) %>%
                                  filter(!(chr %in% c('chrY','chrX','chrM'))) %>% filter(quer/(end-strt)>=quer_prop)
    
    # percentile_99_file <- paste0(dir,'/',callset,'/99_percentile.avg_pct_int_',quer_prop)
    # pct_int_thrhld <- fread(input = percentile_99_file, col.names = c('window','99_percentile'), colClasses = c('numeric','numeric')) %>% 
    #                   filter(window==winsize) %>% 
    #                  select(2) %>% as.numeric()
    
    # pct_int_tbl <- windows.introgressed_bases %>% mutate(pct_int = intr_bp/quer/sample_size)
    # pct_int_thrhld <- pct_int_tbl$pct_int %>% quantile(probs=c(0.01)) %>% as.numeric()
    
    
    print(paste(winsize, pct_int_thrhld,sep=' '))
    
    n_quer <- nrow(windows.introgressed_bases)
    n_blw_thrhld <- windows.introgressed_bases %>%
                    mutate(pct_int=(intr_bp)/(quer)/(sample_size)) %>%
                    filter(pct_int<=pct_int_thrhld) %>%
                    nrow()
    prop_blw_thrhld <- n_blw_thrhld/n_quer
    
    dt.prop_blw_thrhld <- rbind(dt.prop_blw_thrhld, data.table(winsize,n_quer,n_blw_thrhld,prop_blw_thrhld))
  }
  return(dt.prop_blw_thrhld)
}


bootstrap.fn <- function(callset, sample_size, min_window, quer_prop){
  dt.bootstrap.prop_blw_thrhld <- data.table()
  #pct_int_thrhld <- 0.0007762471 

  dir <- '~/DATALab/NeanderthalSeq/IBDmix/desert_test/RealData/'
  callset <- callset #'callset_ALL.neand_ambig'
  sample_size <- sample_size #3046
    
  pct_int_tbl <- fread(input = paste0(dir,'/',callset,'/','windows.8MB.100kb.bed.introgressed_bases_',quer_prop),
                                        header=FALSE,
                                        col.names = c('chr','strt','end','drop','quer','intr_bp')) %>%
                                  filter(!(chr %in% c('chrY','chrX','chrM'))) %>% filter(quer/(end-strt)>=quer_prop) %>%
                  mutate(pct_int = intr_bp/quer/sample_size)
  pct_int_thrhld <- pct_int_tbl$pct_int %>% quantile(probs=c(0.01)) %>% as.numeric() %>% log10()
  pct_int_thrhld <- 10 ^ round(pct_int_thrhld,digits = 2)
  
    for(winsize in seq(from=min_window, to = 15, by = 1)){
    winsize <- winsize
    
    
    infile <- paste0(dir,'/',callset,'/', 'windows.',winsize,'MB.100kb.bed.introgressed_bases_',quer_prop)
    
    windows.introgressed_bases <- fread(input = infile,
                                        header=FALSE,
                                        col.names = c('chr','strt','end','drop','quer','intr_bp')) %>%
                                  filter(!(chr %in% c('chrY','chrX','chrM')))
    
    
    bs.windows.introgressed_bases <- sample_n(tbl = windows.introgressed_bases, size = nrow(windows.introgressed_bases), replace = TRUE)
    #bs.windows.introgressed_bases <- sample_n(tbl = windows.introgressed_bases, size = 50, replace = TRUE)
    
    bs.windows.introgressed_bases <- bs.windows.introgressed_bases %>% filter(quer/(end-strt)>=quer_prop)
    
    # percentile_99_file <- paste0(dir,'/',callset,'/99_percentile.avg_pct_int_',quer_prop)
    # pct_int_thrhld <- fread(input = percentile_99_file, col.names = c('window','99_percentile'), colClasses = c('numeric','numeric')) %>% 
    #                   filter(window==winsize) %>% 
    #                   select(2) %>% as.numeric()
    
    # pct_int_tbl <- windows.introgressed_bases %>% mutate(pct_int = intr_bp/quer/sample_size)
    # pct_int_thrhld <- pct_int_tbl$pct_int %>% quantile(probs=c(0.01)) %>% as.numeric()

    n_quer <- nrow(bs.windows.introgressed_bases)
    n_blw_thrhld <- bs.windows.introgressed_bases %>%
                    mutate(pct_int=(intr_bp)/(quer)/(sample_size)) %>%
                    filter(pct_int<pct_int_thrhld) %>%
                    nrow()
    
    prop_blw_thrhld <- n_blw_thrhld/n_quer
    
    dt.bootstrap.prop_blw_thrhld <- rbind(dt.bootstrap.prop_blw_thrhld, data.table(winsize,n_quer,n_blw_thrhld,prop_blw_thrhld))
  }
  return(dt.bootstrap.prop_blw_thrhld)
}


CI.95.fn <- function(reps, callset, sample_size, min_window, quer_prop){
  dt.CI.95 <- data.table()
  count <- 1
  while(count<=reps){
  #dt.bs <- bootstrap.fn(callset = 'callset_ALL.neand_ambig', sample_size = 2992+56)
  dt.bs <- bootstrap.fn(callset = callset, sample_size = sample_size, min_window = min_window, quer_prop)
  dt.CI.95 <- rbind(dt.CI.95, dt.bs)
  count <- count+1
  }
  return(dt.CI.95)
}



```


```{r}

# Calculate the proportion of queryable windows w/ cM~1 that are bewlo the pct_int_thrhld
EUR_EAS_AFR.RD.prop_blw_thrhld <- Prop_blw_thrhld.fn(callset = 'EUR_EAS_AFR', sample_size = 1511, min_window = 1, quer_prop = 0.75)
EUR_EAS_YRI.RD.prop_blw_thrhld <- Prop_blw_thrhld.fn(callset = 'EUR_EAS_YRI', sample_size = 1115, min_window = 1, quer_prop = 0.75)
EUR_EAS.RD.prop_blw_thrhld <- Prop_blw_thrhld.fn(callset = 'EUR_EAS', sample_size = 1007, min_window = 1, quer_prop = 0.75)

```


```{r}


Bootstrapped.prop_blw_thrhld <- CI.95.fn(reps = 100, callset = 'EUR_EAS_YRI', sample_size = 1115, min_window = 1, quer_prop = 0.75)

CI <- data.table()
for( i in seq(from=1, to=15, by=1)){
  ci <- Bootstrapped.prop_blw_thrhld[winsize==i]$prop_blw_thrhld %>% quantile(probs=c(0.025, 0.975), na.rm=TRUE)
  #ci <- t.test(Bootstrapped.prop_blw_thrhld[winsize==i]$prop_blw_thrhld)$conf.int[1:2]
  CI <- rbind(CI, data.table(winsize=i, lower=ci[1], upper=ci[2]))
}
CI <- replace_na(CI,list(lower=0, upper=0))


```


```{r}
EUR_EAS_YRI.SimData.prop_blw_thrhld <- fread('~/DATALab/NeanderthalSeq/IBDmix/desert_test/Tenn_base_sim/n1_0.03_AFR_216_EUR_1006_EAS_1008/IBDmixCalls/IntroSeg.ALL.D4E0.002.ALL.50kb.bed.5_to_15Mb.prop_blw_thrhld_0.0005',col.names = c('mdl','winsize','n_blw_thrhld','prop_blw_thrhld','n1','n2','admix'))

EUR_EAS_AFR.SimData.prop_blw_thrhld <- fread('~/DATALab/NeanderthalSeq/IBDmix/desert_test/Tenn_base_sim/n1_0.03_AFR_1008_EUR_1006_EAS_1008/IBDmixCalls/IntroSeg.ALL.D4E0.002.ALL.50kb.bed.5_to_15Mb.prop_blw_thrhld_0.00126',col.names = c('mdl','winsize','n_blw_thrhld','prop_blw_thrhld','n1','n2','admix'))
```


```{r}
ggplot() + theme_bw() + geom_line(data=RD.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="dashed") + geom_ribbon(data=CI,aes(x=winsize, ymin=lower, ymax=upper), fill="grey", alpha=0.75)

ggplot() + theme_classic() + 
  geom_line(data=EUR_EAS.RD.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="dashed") + 
  geom_ribbon(data=EUR_EAS.CI,aes(x=winsize, ymin=lower, ymax=upper, fill="EUR_EAS"), alpha=0.75) + 
  
  geom_line(data=EUR_EAS_YRI.RD.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="dashed") + 
  geom_ribbon(data=EUR_EAS_YRI.CI,aes(x=winsize, ymin=lower, ymax=upper, fill="EUR_EAS_YRI"), alpha=0.75) + 
  
  geom_line(data=EUR_EAS_AFR.RD.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="dashed") + 
  geom_ribbon(data=EUR_EAS_AFR.CI,aes(x=winsize, ymin=lower, ymax=upper, fill="EUR_EAS_AFR"), alpha=0.75) +
  
  # geom_line(data=EUR_EAS_YRI.SimData.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="solid", color="black") +
  # geom_line(data=EUR_EAS_AFR.SimData.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="solid", color="orange4") +

  geom_line(data=Sstar.prop_blw_thrhld, aes(x=winsize, y=prop_blw_thrhld), linetype="dashed", color="yellow4") +
  geom_ribbon(data=Sstar.prop_blw_thrhld.CI,aes(x=Winsize, ymin=lwr, ymax=upr), fill="yellow4", alpha=0.75) +
  coord_cartesian(xlim=c(3,8), ylim=c(0.0,0.1), expand = FALSE)
```


```{r Simulated Data}

EUR_EAS_YRI.SimData <- fread(cmd = 'gzcat ~/DATALab/NeanderthalSeq/IBDmix/desert_test/Tenn_base_sim/n1_0.03_AFR_216_EUR_1006_EAS_1008/IBDmixCalls/IntroSeg.ALL.D4E0.002.ALL.50kb.bed.5_to_15Mb.gz',
                 col.names = c('chr','strt','end','winsize','admix1','admix2'))

EUR_EAS_AFR.SimData <- fread(cmd = 'gzcat ~/DATALab/NeanderthalSeq/IBDmix/desert_test/Tenn_base_sim/n1_0.03_AFR_1008_EUR_1006_EAS_1008/IBDmixCalls/IntroSeg.ALL.D4E0.002.ALL.50kb.bed.5_to_15Mb.gz',
                 col.names = c('chr','strt','end','winsize','admix1','admix2'))

SimData.prop_blw_thrhld <- data.table(NULL)

for(ws in seq(5,15,by = 1)){
    #EUR_EAS_YRI
    pct_int_thrhld <- 0.0007762471
    sample_size <- 1115
    # #EUR_EAS_AFR
    # pct_int_thrhld <- 0.0012589
    # sample_size <- 1511
  
      #ws <- 5
    pct_int_tbl <- SimData %>% filter(winsize == ws) %>% group_by(chr) %>% summarise(pct_int=sum(end-strt)/(ws*1000000)/sample_size) %>% as.data.table()
#    pct_int_thrhld <- pct_int_tbl$pct_int %>% quantile(probs=c(0.01)) %>% as.numeric()

    #n_quer <- nrow(pct_int_tbl)
    n_quer <- 5000
    
    n_blw_thrhld <- pct_int_tbl %>%
                    filter(pct_int<pct_int_thrhld) %>%
                    nrow()
    
    prop_blw_thrhld <- n_blw_thrhld/n_quer
    
    SimData.prop_blw_thrhld <- rbind(SimData.prop_blw_thrhld, data.table(ws,n_quer,n_blw_thrhld,prop_blw_thrhld))
            
}

mse(predicted = SimData.prop_blw_thrhld[ws<=10]$prop_blw_thrhld,actual = RD.prop_blw_thrhld[winsize<=10 & winsize>=5]$prop_blw_thrhld )

mse(predicted = Sstar.prop_blw_thrhld[winsize<=10 & winsize>=5]$prop_blw_thrhld,actual = RD.prop_blw_thrhld[winsize<=10 & winsize>=5]$prop_blw_thrhld )

```

