---
title: "Untitled"
author: "Aaron Wolf"
date: "11/27/2018"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(RColorBrewer)

```

####
```{r Size distribution of shared haplotypes in Emprical Data}

dirs <- list.dirs('~/DATALab/NeanderthalSeq/IBDmix')

#for(i in dirs[2:5]){
#  print(i)
  i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/" 
  i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/" 
  dirpath <- i
  setwd(dirpath)


AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID' ,'pop','anc','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)

####
nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)

nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)

nonAFR.total.unmerged <- fread('EUR_EAS_SAS_AMR_calls.bed', col.names = c('chr','strt','end','ID', 'pop','anc'))

# 
# #####
# SAN.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator SANcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID' ,'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# SAN.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator SANcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)
# 
# nonSAN.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed SANcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# nonSAN.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed SANcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)
#####

# #####
# AFR.EURshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EURcalls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcalls.bed EAScalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.EUR_EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EUR_EAScalls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)


# ######################
# AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID' ,'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)
# 
# ####
# nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)
# 
# ####
# AFR.EURshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EURcalls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcalls.bed EAScalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.EUR_EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAScalls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)
# ######################


p_0.001.a <- 
  ggplot() + 
  theme_bw() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=2, alpha=0.9) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=2, alpha=0.9) +
  geom_density(data = nonAFR.total.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.total.unmerged", fill="nonAFR.total.unmerged"), size=2, alpha=0.7) +
  coord_cartesian(xlim=c(3.4,7), expand = c(0)) +
  scale_x_continuous(breaks=seq(3.5,7,by = 1), labels=seq(3.5,7,by = 1)) +
  ggtitle('Size distribution of segments from Empirical data') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  #  theme_bw(base_size=34) +
  xlab('Segment Length ( ln(kb) )')+
  theme(plot.title=element_text(face="bold", size=20),
        axis.text=element_text(face="bold", size=16),
        axis.title=element_text(face="bold", size=16)
        )
  
  
  
#######


ggplot() + theme_bw() + 
  stat_ecdf(data = nonAFR.total.unmerged, aes(x = (end-strt)/1000, color="nonAFR"), geom="step") +  
  stat_ecdf(data = AFR.unshared.unmerged, aes(x = (end-strt)/1000, color="AFR.unique"), geom="step") + 
  stat_ecdf(data = AFR.shared.unmerged, aes(x = (end-strt)/1000, color="AFR.shared"), geom="step") + 
  coord_cartesian(xlim=c(25,300), expand = FALSE) + 
  scale_x_continuous(breaks=seq(20,300,20)) + 
  scale_y_continuous(breaks=seq(0,1.0,0.2)) + 
  scale_color_brewer(type = 'qual', palette = 'Dark2')


ggplot() + theme_bw() + 
  stat_ecdf(data = Deni.dt %>% filter(!pop %in% c('ACB', 'ASW') ), aes(x = size/1000, color=anc), geom="step") +  
  #stat_ecdf(data = AFR.unshared.unmerged, aes(x = (end-strt)/1000, color="AFR.unique"), geom="step") + 
  #stat_ecdf(data = AFR.shared.unmerged, aes(x = (end-strt)/1000, color="AFR.shared"), geom="step") + 
  coord_cartesian(xlim=c(25,300), expand = FALSE) + 
  scale_x_continuous(breaks=seq(20,300,20)) + 
  scale_y_continuous(breaks=seq(0,1.0,0.2)) + 
  ggtitle('Denisovan Calls segment size ECDF', ) +
  scale_color_brewer(type = 'qual', palette = 'Dark2')


  ggplot() + 
  theme_bw() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=2, alpha=0.9) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=2, alpha=0.7) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.unshared.unmerged", fill="nonAFR.unshared.unmerged"), size=2, alpha=0.3) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), color="nonAFR.shared.unmerged", fill="nonAFR.shared.unmerged"), size=2, alpha=0.3) +
  coord_cartesian(xlim=c(3.4,7), expand = c(0)) +
  scale_x_continuous(breaks=seq(3.5,7,by = 1), labels=seq(3.5,7,by = 1)) +
  ggtitle('Size distribution of segments from Empirical data') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  #  theme_bw(base_size=34) +
  xlab('Segment Length ( ln(kb) )')+
  theme(plot.title=element_text(face="bold", size=20),
        axis.text=element_text(face="bold", size=16),
        axis.title=element_text(face="bold", size=16)
        )

  ggplot() + 
  theme_bw() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), size=1, alpha=0.9) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), size=1, alpha=0.7) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), size=1, alpha=0.3) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), size=1, alpha=0.3) +
  coord_cartesian(xlim=c(3.4,7), expand = c(0)) +
  ggtitle('Size distribution of segments from Empirical data') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  #  theme_bw(base_size=34) +
  theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )

######



p_0.001.c <- ggplot() + 
  geom_density(data = AFR.EUR_EASshared.unmerged , aes(x=log((end-strt)/1000), fill="AFR.EUR_EASshared.unmerged "), alpha=0.5) +
  geom_density(data = AFR.EURshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EURshared.unmerged"), alpha=0.5) +
  geom_density(data = EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.EASshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('Size distribution of segments from Empirical data') +
  theme()

print('generate graph')
#pdf("EmpiricalSegments_segmentlen.pdf", width = 16, height = 9)
pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/EmpiricalSegments_segmentlen.pdf", width = 16, height = 9)
#grid.arrange(p_0.001.a, p_0.001.c, ncol=2)
grid.arrange(p_0.001.a, ncol=1)
dev.off()

######################################################
#grid.arrange(p_0.001.a, p_0.001.b, p_0.001.c, ncol=3)


# p_0.001 <- ggplot() + 
#   geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), alpha=0.5) +
#   geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = nonAFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('p_0.001') +
#   theme()


# AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator YRIcall.bed EUR_EAS_SAS_AMR_call.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator YRIcall.bed EUR_EAS_SAS_AMR_call.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==0)
# 
# ####
# nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator EUR_EAS_SAS_AMR_call.bed YRIcall.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==1)
# 
# nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator EUR_EAS_SAS_AMR_call.bed YRIcall.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==0)
# 
# ####
# AFR.EURshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator YRIcall.bed EURcall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)
# 
# EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator EURcall.bed EAScall.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.EUR_EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.2 --indicator YRIcall.bed EUR_EAScall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)


# p_0.2 <- ggplot() + 
#   geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), alpha=0.5) +
#   geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = nonAFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('p_0.2') +
#   theme()


# p_0.2.a <- ggplot() + 
#   geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('p_0.2') +
# #   theme()
# # 
# # p_0.2.b <- ggplot() + 
#   geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), alpha=0.5) +
#   geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged "), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('p_0.2') +
#   theme()
# 
# p_0.2.c <- ggplot() + 
#   geom_density(data = AFR.EUR_EASshared.unmerged , aes(x=log((end-strt)/1000), fill="AFR.EUR_EASshared.unmerged "), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EURshared.unmerged"), alpha=0.5) +
#   geom_density(data = EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.EASshared.unmerged"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('p_0.2') +
#   theme()

#ggsave(filename = "plot.pdf", width = 16, height = 9, path = dirpath)
#####################################################################

# rm(list=ls(pattern = '.unmerged'))
# 
# }


```


```{r Size distribution of shared haplotypes in Simulated Data Data w/o back-migration}


  i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0/overlaps/"
  #i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005/overlaps/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005/TreeCalls/"
  dirpath <- i
  setwd(dirpath)
  
AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)

####
nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)


# ####
# AFR.EURshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)
# 
# EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR.D4E0.002.ALL.30kb.bed IntroSeg.ASN.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)
# 
# AFR.EUR_EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)



p_0.001.a <- 
  ggplot() + 
  theme_bw() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=2, alpha=0.9) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=2, alpha=0.7) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.unshared.unmerged", fill="nonAFR.unshared.unmerged"), size=2, alpha=0.3) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), color="nonAFR.shared.unmerged", fill="nonAFR.shared.unmerged"), size=2, alpha=0.3) +
  coord_cartesian(xlim=c(3.4,7), expand = c(0)) +
  scale_x_continuous(breaks=seq(3.5,7,by = 1), labels=seq(3.5,7,by = 1)) +
  ggtitle('Size distribution of segments from Simulated data') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  #  theme_bw(base_size=34) +
  xlab('Segment Length ( ln(kb) )')+
  theme(plot.title=element_text(face="bold", size=20),
        axis.text=element_text(face="bold", size=16),
        axis.title=element_text(face="bold", size=16)
        )

############

  ggplot() + 
  theme_bw() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), size=1, alpha=0.7) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), size=1, alpha=0.7) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), size=1, alpha=0.7) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), size=1, alpha=0.7) +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Size distribution of segments from Simulated data') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  #  theme_bw(base_size=34) +
  theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )


  ggplot() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), alpha=0.5) +
  geom_density(data = nonAFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), alpha=0.5) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('Size distribution of segments from Simulated data w/ back-migration (mEuAf_0.00005)') +
  theme()

###########


# p_0.001.c <- ggplot() + 
#   geom_density(data = AFR.EUR_EASshared.unmerged , aes(x=log((end-strt)/1000), fill="AFR.EUR_EASshared.unmerged "), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EURshared.unmerged"), alpha=0.5) +
#   geom_density(data = EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.EASshared.unmerged"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,7)) +
#   ggtitle('Size distribution of segments from Empirical data') +
#   theme()


#pdf("SimulatedSegments_segmentlen.pdf", width = 16, height = 9)
pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0_segmentlen.pdf", width = 16, height = 9)
#pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_segmentlen.pdf", width = 16, height = 9)
#grid.arrange(p_0.001.a, p_0.001.c, ncol=2)
grid.arrange(p_0.001.a, ncol=1)
dev.off()

```
####


```{r SFS Real Data}

# dirs <- list.dirs('~/DATALab/NeanderthalSeq/IBDmix')
# 
# for(i in dirs[2:5]){
#     print(i)
  i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/" 
  dirpath <- i
  setwd(dirpath)

#print('Sze Distribution of Segements')

AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID' ,'pop','anc','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)


nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator')) %>% filter(indicator==1)

nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_calls.bed AFRcalls.bed.merged', col.names = c('chr','strt','end','ID', 'pop','anc','bases','indicator'))

nonAFR.total.unmerged <- fread('EUR_EAS_SAS_AMR_calls.bed', col.names = c('chr','strt','end','ID', 'pop','anc'))


EUR.total.sum <- fread('EURcalls.bed', select = 1:3, col.names = c('chr','strt','end')) %>% 
                  summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN.total.sum <- fread('EAScalls.bed', select = 1:3, col.names = c('chr','strt','end')) %>% 
                  summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN_EUR.total.ratio <- ASN.total.sum/EUR.total.sum

EUR.minusAFR.sum <- fread(cmd = 'bedops --ec -n EURcalls.bed YRIcalls.bed.merged', select = 1:3, col.names = c('chr','strt','end')) %>%
                    summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN.minusAFR.sum <- fread(cmd = 'bedops --ec -n EAScalls.bed YRIcalls.bed.merged', select = 1:3, col.names = c('chr','strt','end')) %>%
                    summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN_EUR.minusAFR.ratio <- ASN.minusAFR.sum/EUR.minusAFR.sum
  
# #####
# print('Count of segments that overlap')
# # AFR.EURshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcalls.bed EURcalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# # 
# # AFR.EASshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcalls.bed EAScalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# # 
# # EUR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EURcalls.bed YRIcalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# # 
# # EAS.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EAScalls.bed YRIcalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# #####

AFR.nonAFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcalls.bed EUR_EAScalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)

nonAFR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EUR_EAScalls.bed YRIcalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)

# ####
# SAN.nonAFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count SANcalls.bed EUR_EAScalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# 
# nonAFR.SANshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EUR_EAScalls.bed SANcalls.bed', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','count')) %>% filter(count>0)
# ####

nrow.AFR <- fread('YRIcalls.bed') %>% nrow() 
nrow.SAN <- fread('SANcalls.bed') %>% nrow()  
nrow.EUR <- fread('EURcalls.bed') %>% nrow()
nrow.EAS <- fread('EAScalls.bed') %>% nrow()
nrow.nonAFR <- fread('EUR_EAScalls.bed') %>% nrow()

# ####
# median(EUR.AFRshared.unmerged.count$count)/nrow(AFR.EURshared.unmerged.count)
# median(EAS.AFRshared.unmerged.count$count)/nrow(AFR.EASshared.unmerged.count)
# median(AFR.EASshared.unmerged.count$count)/nrow(EAS.AFRshared.unmerged.count)
# median(AFR.EURshared.unmerged.count$count)/nrow(EUR.AFRshared.unmerged.count)
# 
# 
# 
# print('Count of segments that overlap a merged area')
# AFR.EURshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcalls.bed.merged EURcalls.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# AFR.EASshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcalls.bed.merged EAScalls.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EUR.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EURcalls.bed.merged YRIcalls.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EAS.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EAScalls.bed.merged YRIcalls.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# ####


print('Count of shared/unshared segements w/in that segments population. i.e. For a non-shared YRI segment, how frequent is it in the YRI populations?')

AFR.nonAFRunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EUR_EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)

AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EUR_EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)


#####

# AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator AFRcalls.bed EUR_EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)

# SAN.nonAFRunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator SANcalls.bed EUR_EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# SAN.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator SANcalls.bed EUR_EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# 
# AFR.EURunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EURcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.EURshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EURcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# 
# AFR.EASunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.EASshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
#####


print('Measure how frequent an EUR or EAS segment is in its respective population if it is shared with YRI, but not shared with the other nonAFR pop ; does this explain why YRI-masking has a greater effect on EUR than EAS even though similar rates of overlap?')

 EUR_AFRshared.notEAS <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator EURcalls.bed YRIcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)


EAS_AFRshared.notEUR <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator EAScalls.bed YRIcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - EURcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)
 
nonAFR_AFRshared <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator EUR_EAScalls.bed YRIcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==1) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% summarise(sum(as.numeric(end-strt))/1000000) %>% as.numeric()

#  ##Lu's version
# EUR_AFRshared.notEAS <- fread("bedtools intersect -a YRIcalls.bed.merged -b EURcalls.bed.merged | sort-bed - | bedtools subtract -a - -b EAScalls.bed.merged | bedops --merge -",
#                                   col.names = c('chr','strt','end')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# EUR_AFRshared.total <- fread("bedtools intersect -a YRIcalls.bed.merged -b EURcalls.bed.merged | sort-bed - | bedops --merge -",
#                                   col.names = c('chr','strt','end')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# ##Lu's version
# EAS_AFRshared.notEUR <- fread("bedtools intersect -a YRIcalls.bed.merged -b EAScalls.bed.merged | sort-bed - | bedtools subtract -a - -b EURcalls.bed.merged | bedops --merge - ",
#                                   col.names = c('chr','strt','end')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# EAS_AFRshared.total <- fread("bedtools intersect -a YRIcalls.bed.merged -b EAScalls.bed.merged | sort-bed - | bedops --merge -",
#                                   col.names = c('chr','strt','end')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()



# print('On average, how much extra is removed in EUR due to YRI masking than in EAS?')
# EUR_AFRshared.notEAS %>% group_by() %>% summarise(sum=sum(as.numeric(end-strt))/1000000/503)
# EAS_AFRshared.notEUR %>% group_by() %>% summarise(sum=sum(as.numeric(end-strt))/1000000/504)


plot.theme <-theme(
        #legend.position="none"m
        legend.text=element_text(size=1),
        #panel.grid.major=element_line(color="black"),
        panel.grid=element_blank(),
        axis.line.x=element_line(color="black", size=2),
        axis.line.y=element_line(color="black",size=2),
        plot.title=element_text(face="bold", color="black", size=42, hjust = 0.5, family = "Helvetica"),
        axis.text=element_text(face="bold", color="black", size=42, family = "Helvetica"),
        axis.title=element_text(face="bold", color="black", size=42, family = "Helvetica")
        )


### Size Distribution

p_0.001.a <- 
  ggplot() + 
  theme_classic() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = nonAFR.total.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.total.unmerged", fill="nonAFR.total.unmerged"), size=4, alpha=0.2) +
  coord_cartesian(xlim=c(3.97,7), ylim=c(0,3.5), expand = FALSE) +
  scale_x_continuous(breaks=seq(4,7,by = 1), labels=seq(4,7,by = 1)) +
  scale_y_continuous(breaks = seq(0,5,by=1), labels = scales::number_format(accuracy = 0.1)) +
  ggtitle('Distribution of Segment Lengths\n') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  xlab('\nSegment Length ( ln(kb) )') +
  ylab('density\n') +
  plot.theme


#############
p_0.001.b <-   ggplot() + 
  theme_classic() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=2, alpha=0.9) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=2, alpha=0.7) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.unshared.unmerged", fill="nonAFR.unshared.unmerged"), size=2, alpha=0.3) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), color="nonAFR.shared.unmerged", fill="nonAFR.shared.unmerged"), size=2, alpha=0.3) +
  coord_cartesian(xlim=c(3.4,7), expand = FALSE) +
  scale_x_continuous(breaks=seq(3.5,7,by = 1), labels=seq(3.5,7,by = 1)) +
  ggtitle('Distribution of Segment Lengths') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  xlab('Segment Length ( ln(kb) )') +
  plot.theme
#############

############
### SFS 
# p1 <-
#   ggplot() +
#   theme_classic() +
# #  geom_histogram(data = nonAFR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="nonAFR.AFRshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
#   geom_histogram(data = AFR.nonAFRshared.unmerged.count, aes(x=count/nrow.nonAFR, fill="AFR.nonAFRshared.unmerged.count", y=..density..), color="black", size=1, bins=30, alpha=0.7) +
#   coord_cartesian(xlim=c(0,0.005), expand = FALSE) +
#   scale_x_continuous(labels = c('0','1e-3','2e-3','3e-3','4e-3','5e-3')) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   ggtitle('Frequency of AFR Segment in nonAFR Population') +
#   xlab('Frequency') +
#   plot.theme
###############

######################    
# 
# ggplot() + theme_bw() =
#   geom_histogram(data = nonAFR.SANshared.unmerged.count, aes(x=count/nrow.SAN, fill="nonAFR.SANshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
#   geom_histogram(data = SAN.nonAFRshared.unmerged.count, aes(x=count/nrow.nonAFR, fill="SAN.nonAFRshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
#   coord_cartesian(xlim=c(0,0.005)) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   ggtitle('Count of segments that overlap') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))  
# 
# 
#   ggplot() +
#   theme_bw() +
#   geom_histogram(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count", y=..density..), alpha=0.5, bins=50) +
#   geom_histogram(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count", y=..density..), alpha=0.5, bins=50) +
#   geom_histogram(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count", y=..density..), alpha=0.5, bins=50) +
#   geom_histogram(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.EAS, fill="AFR.EASshared.unmerged.count", y=..density..), alpha=0.5, bins=50) +
#   coord_cartesian(xlim=c(0,0.005)) +
#   ggtitle('Count of segments that overlap') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
# 
# 
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.EAS, fill="AFR.EASshared.unmerged.count", y=..count..), alpha=0.5) +
#   coord_cartesian(xlim=c(0,0.005)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
#   
#   ggplot() +
#   geom_density(data = rbind(EUR.AFRshared.unmerged.count, EAS.AFRshared.unmerged.count), aes(x=count/nrow(rbind(AFR.EURshared.unmerged.count, AFR.EASshared.unmerged.count)), fill="nonAFR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = rbind(AFR.EURshared.unmerged.count, AFR.EASshared.unmerged.count), aes(x=count/nrow(rbind(EUR.AFRshared.unmerged.count, EAS.AFRshared.unmerged.count)), fill="AFR.nonAFRshared.unmerged.count"), alpha=0.5) +
# #  coord_cartesian(xlim=c(0,500)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
# 
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.EAS, fill="AFR.EASshared.unmerged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,0.005)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
#   
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count, fill="EUR.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count, fill="EAS.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count, fill="AFR.EURshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count, fill="AFR.EASshared.unmerged.count", y=..count..), alpha=0.5) +
#   coord_cartesian(xlim=c(0,500)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
#   
#   
# ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count, fill="EUR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count, fill="EAS.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count, fill="AFR.EURshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count, fill="AFR.EASshared.unmerged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,500)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
######################
  

p3 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('Below 10%', 'Above 10%'), 
                             c(AFR.nonAFRshared.count %>% filter(count<(0.1*108)) %>% nrow()/nrow(AFR.nonAFRshared.count), 
                               AFR.nonAFRshared.count %>% filter(count>(0.1*108)) %>% nrow()/nrow(AFR.nonAFRshared.count))
                             ) %>% 
                  setnames(c('category','proportion')),
           aes(x=category, y=proportion, fill=category), stat = "identity", width = 0.5) +
  scale_x_discrete(limits=c('Below 10%', 'Above 10%')) +
  scale_y_continuous(breaks = seq(0,1,0.2), labels= seq(0,1,0.2)) +
  coord_cartesian(ylim=c(0.045,1.0),expand = TRUE) +
  scale_fill_manual(values=c('Below 10%'='dodgerblue4','Above 10%'='orange3')) +
  ggtitle('Frequency of African Segments in Africans\n') +
  xlab('\nFrequency') +
  ylab('Proportion of Total Calls\n') +
  plot.theme


########################

  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('Below 10%', 'Above 10%'), 
                             c(AFR.nonAFRshared.count %>% filter(count<(0.1*504)) %>% nrow()/nrow(AFR.nonAFRshared.count %>% filter(count <= 504)), 
                               AFR.nonAFRshared.count %>% filter(count>(0.1*504)) %>% nrow()/nrow(AFR.nonAFRshared.count %>% filter(count <= 504)))
                             ) %>% 
                  setnames(c('category','proportion')),
           aes(x=category, y=proportion, fill=category), stat = "identity", width = 0.5) +
  scale_x_discrete(limits=c('Below 10%', 'Above 10%')) +
  scale_y_continuous(breaks = seq(0,1,0.2), labels= seq(0,1,0.2)) +
  coord_cartesian(ylim=c(0.045,1.0),expand = TRUE) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  ggtitle('Frequency of African Segments in Africans\n') +
  xlab('\nFrequency') +
  ylab('Proportion of Total Calls\n') +
  plot.theme




#   
# 
#   ggplot() +
#   theme_bw() +
# #  geom_density(data=AFR.nonAFRunshared.count, aes(x=count, fill="AFR.nonAFR.unshared"), size=1, alpha=0.7) + 
#   geom_density(data=AFR.nonAFRshared.count, aes(x=count, fill="AFR.nonAFR.shared"),size=1, alpha=0.7) + 
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   coord_cartesian(xlim=c(0,200)) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   theme(plot.title=element_text(face="bold", size=20),
#         axis.text=element_text(face="bold", size=16),
#         axis.title=element_text(face="bold", size=16)
#         )
# 
#   ggplot() +
#   theme_bw() +
#   geom_density(data=SAN.nonAFRunshared.count, aes(x=count, fill="SAN.nonAFR.unshared"), size=1, alpha=0.7) + 
#   geom_density(data=SAN.nonAFRshared.count, aes(x=count, fill="SAN.nonAFR.shared"),size=1, alpha=0.7) + 
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   coord_cartesian(xlim=c(0,100)) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
# 
# 
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count, fill="AFR.EUR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count, fill="AFR.EUR.shared"), alpha=0.75) + 
#   geom_density(data=AFR.EASunshared.count, aes(x=count, fill="AFR.EAS.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EASshared.count, aes(x=count, fill="AFR.EAS.shared"), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,200)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
# 
# ggplot() +
#   geom_density(data=AFR.nonAFRunshared.count, aes(x=count/nrow(AFR.nonAFRunshared.count), fill="AFR.nonAFR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.nonAFRshared.count, aes(x=count/nrow(AFR.nonAFRshared.count), fill="AFR.nonAFR.shared"), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,500)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
# 
#     ggplot() +
#   geom_density(data=AFR.nonAFRunshared.count, aes(x=count, fill="AFR.nonAFR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.nonAFRshared.count, aes(x=count, fill="AFR.nonAFR.shared"), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,500)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
#   
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count/nrow(AFR.EURunshared.count), fill="AFR.EUR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count/nrow(AFR.EURshared.count), fill="AFR.EUR.shared"), alpha=0.75) + 
#   geom_density(data=AFR.EASunshared.count, aes(x=count/nrow(AFR.EASunshared.count), fill="AFR.EAS.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EASshared.count, aes(x=count/nrow(AFR.EASshared.count), fill="AFR.EAS.shared"), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,500)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
#   
#   
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count/nrow(AFR.EURunshared.count), fill="AFR.EUR.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count/nrow(AFR.EURshared.count), fill="AFR.EUR.shared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.EASunshared.count, aes(x=count/nrow(AFR.EASunshared.count), fill="AFR.EAS.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.EASshared.count, aes(x=count/nrow(AFR.EASshared.count), fill="AFR.EAS.shared", y=..count..), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,500)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
########################  


p4 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('ASN_EUR.total.ratio', 'ASN_EUR.minusAFR.ratio'), 
                             c(ASN_EUR.total.ratio, ASN_EUR.minusAFR.ratio)) %>% 
                  setnames(c('category','ratio')),
           aes(x=category, y=ratio, fill=category), stat = "identity", width=0.5 ) +
  geom_hline(yintercept = 1, linetype='dashed', size = 2) +
  scale_x_discrete(limits=c('ASN_EUR.total.ratio', 'ASN_EUR.minusAFR.ratio'), labels=c('Unmaksed', 'Masked')) +
  scale_y_continuous(breaks = seq(0,1.5,by = 0.2), labels=seq(0,1.5,by = 0.2)) +
  coord_cartesian(ylim=c(0.06,1.4), expand = TRUE) +
  scale_fill_manual(values=c('ASN_EUR.total.ratio'='dodgerblue4', 'ASN_EUR.minusAFR.ratio'='orange3')) +
  ggtitle('Masking African Sequence\n') +
  xlab('\nCategory') +
  ylab('Ratio of Called Sequence\n') +
  plot.theme



p5 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('EUR_AFR_Shared', 'EAS_AFR_Shared'),
                             c(EUR_AFRshared.notEAS %>% mutate(len=end-strt) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric(),
                               EAS_AFRshared.notEUR %>%  mutate(len=end-strt) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric() )
                            # c(EUR_AFRshared.notEAS %>% mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/(EUR.total.sum/1000000) %>% as.numeric(),
                            #   EAS_AFRshared.notEUR %>%  mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/(ASN.total.sum/1000000) %>% as.numeric())
                            # c(EUR_AFRshared.notEAS/EUR_AFRshared.total,
                            #   EAS_AFRshared.notEUR/EAS_AFRshared.total)
                             ) %>%
                  setnames(c('category','sum_Mb')),
           aes(x=category, y=sum_Mb, fill=category), stat = "identity", width=0.5 ) +
  scale_x_discrete(limits=c('EAS_AFR_Shared', 'EUR_AFR_Shared'), labels=c('EAS and AFR', 'EUR and AFR')) +
  #  scale_y_discrete(limits = seq(0,0.1,by = 0.025), labels=seq(0,0.1,by = 0.025)) +
  coord_cartesian(ylim=c(0.0045,0.3)) +
  scale_fill_manual(values=c('EAS_AFR_Shared'='dodgerblue4', 'EUR_AFR_Shared'='orange3')) +
  ggtitle('Amount of Exclusively Shared Sequence\n') +
  # coord_cartesian(ylim=c(50,1050), expand=TRUE) +
  xlab('\nPaired Populations') +
  ylab('Proportion of Shared Sequence\n') +
  plot.theme


###################

# ggplot() +
# theme_classic() +
# geom_bar(data = data.table(c('EUR_AFR_Shared', 'EAS_AFR_Shared'), 
#                            c(EUR_AFRshared.notEAS %>% mutate(len=end-strt) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric(), 
#                              EAS_AFRshared.notEUR %>%  mutate(len=end-strt) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric() )
#                            ) %>% 
#                 setnames(c('category','sum_Mb')),
#          aes(x=category, y=sum_Mb, fill=category), stat = "identity", width=0.5 ) +
# scale_x_discrete(limits=c('EAS_AFR_Shared', 'EUR_AFR_Shared'), labels=c('EAS and AFR', 'EUR and AFR')) +
# #  scale_y_discrete(limits = seq(0,0.1,by = 0.025), labels=seq(0,0.1,by = 0.025)) +
# coord_cartesian(ylim=c(0.0045,0.1)) +
# scale_fill_manual(values=c('EAS_AFR_Shared'='dodgerblue4', 'EUR_AFR_Shared'='orange3')) +
# ggtitle('Amount of Exclusively Shared Sequence\n') +
# # coord_cartesian(ylim=c(50,1050), expand=TRUE) +
# xlab('\nPaired Populations') +
# ylab('Proportion of Shared Sequence\n') +
# plot.theme


#   
#   ggplot() + 
#   theme_bw() +
#   geom_density(data=EUR_AFRshared.notEAS, aes(x=count/nrow(EUR_AFRshared.notEAS), fill="EUR_AFRshared.notEAS", y=..count..), size=1, alpha=0.75) + 
#   geom_density(data=EAS_AFRshared.notEUR, aes(x=count/nrow(EAS_AFRshared.notEUR), fill="EAS_AFRshared.notEUR", y=..count..), size=1, alpha=0.75) + 
#   # geom_vline(aes( xintercept = median(EUR.AFRshared.count$count)+5, color="EUR.AFRshared.count"), linetype="twodash", size=2) +
#   # geom_vline(aes(xintercept = median(EAS.AFRshared.count$count)-5, color="EAS.AFRshared.count"), linetype="twodash", size=2) +
# #  coord_cartesian(xlim=c(0,500)) + 
#   ggtitle('Proportion an EUR or EAS segment is shared with YRI and not with the other nonAFR') +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
#   
# 
###################
  
  
# print('generate graph')
# pdf("EmpiricalSegments_LengthAndSFS.pdf", width = 30, height = 9)
# grid.arrange(Empirical.SegmentLen, p1, p3, p4, ncol=4)
# dev.off()

print('generate graph')
pdf("~/Desktop/EmpiricalSegments_SFS.pdf", width = 40, height = 9)
pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/EmpiricalSegments_SegLengthSFS.pdf", width = 40, height = 9)
pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/EmpiricalSegments_SegLengthSFS.pdf", width = 55, height = 9)
#grid.arrange(p1, p3, ncol=2)
#grid.arrange(p_0.001.a, p3, p4, p_0.001.b, ncol=4)
grid.arrange(p_0.001.a,p3,p4, ncol=3)
grid.arrange(p_0.001.a,p3,p4,p5, ncol=4)
dev.off()


# rm(list=ls(pattern = 'merged'))
# 
# }

```



```{r SFS Simulated Data}

  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0/overlaps/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005/overlaps/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0005/overlaps/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0001/overlaps/"

  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0/IBDmixCalls"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.000025/IBDmixCalls/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005/IBDmixCalls/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0005/IBDmixCalls/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0001/IBDmixCalls/"
  # 
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/preOOA/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0_pOOA_0.1/IBDmixCalls/"
  # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/preOOA/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0_pOOA_0.05/IBDmixCalls/"

  # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.000025_preOOA_0.03/IBDmixCalls/"
   # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.000025_preOOA_0.05/IBDmixCalls/"
   # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.000025_preOOA_0.1/IBDmixCalls/"
   # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_preOOA_0.1/IBDmixCalls/"
   # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_preOOA_0.05/IBDmixCalls/"
  # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0005_preOOA_0.1/IBDmixCalls/"
  # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0005_preOOA_0.05/IBDmixCalls/"

 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0005_preOOA_0.0/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.00005_preOOA_0.0/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.000025_preOOA_0.0/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0_preOOA_0.0/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0_preOOA_0.1_t_250/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0_preOOA_0.1_t_150/ibdmix/keep"
 i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0_preOOA_0.1_t_100/ibdmix/keep"
 
 i <- "~/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.00005_preOOA_0.1_t_100/ibdmix/keep"
 i <- "~/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Wenqing/n1_0.05_mEuAf_0.0005_preOOA_0.1_t_100/ibdmix/keep"
 
 

  dirpath <- i
  setwd(dirpath)


# Size Distribution
  
AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)

####
# nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

#nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)

nonAFR.total.unmerged <- fread('IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end'))

EUR.total.sum <- fread('IntroSeg.EUR.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end')) %>% 
                  summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN.total.sum <- fread('IntroSeg.ASN.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end')) %>% 
                  summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN_EUR.total.ratio <- ASN.total.sum/EUR.total.sum

EUR.minusAFR.sum <- fread(cmd = 'bedops --ec -n IntroSeg.EUR.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end')) %>%
                    summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN.minusAFR.sum <- fread(cmd = 'bedops --ec -n IntroSeg.ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end')) %>%
                    summarise(sum(as.numeric(end-strt))) %>% as.numeric()
ASN_EUR.minusAFR.ratio <- ASN.minusAFR.sum/EUR.minusAFR.sum

#####  
# Count of segments that overlap
# AFR.EURshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.5 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed  IntroSeg.EUR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# AFR.EASshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.5 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.ASN.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EUR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.5 --count IntroSeg.EUR.D4E0.002.ALL.30kb.bed IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EAS.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.5 --count IntroSeg.ASN.D4E0.002.ALL.30kb.bed IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
#####

AFR.nonAFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end', 'bases','count')) %>% filter(count>0)

nonAFR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end', 'bases','count')) %>% filter(count>0)

nrow.AFR <- fread('IntroSeg.AFR.D4E0.002.ALL.50kb.bed') %>% nrow()  
nrow.EUR <- fread('IntroSeg.EUR.D4E0.002.ALL.50kb.bed') %>% nrow()
nrow.ASN <- fread('IntroSeg.ASN.D4E0.002.ALL.50kb.bed') %>% nrow()
nrow.nonAFR <- fread('IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed') %>% nrow()

#####
# median(EUR.AFRshared.unmerged.count$count)
# median(EAS.AFRshared.unmerged.count$count)
# median(AFR.EASshared.unmerged.count$count)
# median(AFR.EURshared.unmerged.count$count)

  
# # Count of segments that overlap a merged area
# AFR.EURshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged  IntroSeg.EUR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# AFR.EASshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged IntroSeg.ASN.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EUR.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.EUR.D4E0.002.ALL.30kb.bed.merged IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
# 
# EAS.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.ASN.D4E0.002.ALL.30kb.bed.merged IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)
#####


# Count of shared/unshared segements w/in that segments population. i.e. For a non-shared YRI segment, how frequent is it in the YRI populations?
AFR.nonAFRunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)

AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                 col.names = c('chr','strt','end','count')) %>% filter(count>0)

#####
# AFR.EURunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.EURshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.ASNunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.ASNshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
#                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)
#####

# Measure how frequent an EUR or EAS segment is in its respective population if it is shared with YRI, but not shared with the other nonAFR pop ; does this explain why YRI-masking has a greater effect on EUR than EAS even though similar rates of overlap?

EUR_AFRshared.notEAS <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - IntroSeg.ASN.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)

EAS_AFRshared.notEUR <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - IntroSeg.EUR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)

nonAFR_AFRshared <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==1) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% summarise(sum(as.numeric(end-strt))/1000000) %>% as.numeric()


# ##Lu's version
# EUR_AFRshared.notEAS <- fread("bedtools intersect -a IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged -b IntroSeg.EUR.D4E0.002.ALL.50kb.bed.merged | sort-bed - | bedtools subtract -a - -b IntroSeg.ASN.D4E0.002.ALL.50kb.bed.merged | bedops --merge -",
#                                   col.names = c('chr','strt','end'), colClasses = c('numeric','numeric','numeric')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# EUR_AFRshared.total <- fread("bedtools intersect -a IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged -b IntroSeg.EUR.D4E0.002.ALL.50kb.bed.merged | sort-bed - | bedops --merge -",
#                                   col.names = c('chr','strt','end'), colClasses = c('numeric','numeric','numeric')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# ##Lu's version
# EAS_AFRshared.notEUR <- fread("bedtools intersect -a IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged -b IntroSeg.ASN.D4E0.002.ALL.50kb.bed.merged | sort-bed - | bedtools subtract -a - -b IntroSeg.EUR.D4E0.002.ALL.50kb.bed.merged | bedops --merge - ",
#                                   col.names = c('chr','strt','end'), colClasses = c('numeric','numeric','numeric')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()
# 
# EAS_AFRshared.total <- fread("bedtools intersect -a IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged -b IntroSeg.ASN.D4E0.002.ALL.50kb.bed.merged | sort-bed - | bedops --merge -",
#                                   col.names = c('chr','strt','end'), colClasses = c('numeric','numeric','numeric')) %>% summarise(sum_Mb=sum(end-strt)/1000000) %>% as.numeric()



# # On average, an extra 1.6Mb of sequence is removed in EUR due to YRI masking than in EAS...
# EUR_AFRshared.notEAS %>% group_by() %>% summarise(sum=sum(as.numeric(end-strt))/1000000/503)
# EAS_AFRshared.notEUR %>% group_by() %>% summarise(sum=sum(as.numeric(end-strt))/1000000/504)



plot.theme <- theme(
        #legend.position="none",
        legend.text=element_text(size=1),
        #panel.grid.major=element_line(color="black"),
        panel.grid=element_blank(),
        axis.line.x=element_line(color="black", size=2),
        axis.line.y=element_line(color="black",size=2),
        plot.title=element_text(face="bold", color="black", size=42, hjust = 0.5, family = "Helvetica"),
        axis.text=element_text(face="bold", color="black", size=42, family = "Helvetica"),
        axis.title=element_text(face="bold", color="black", size=42, family = "Helvetica")
        )


#plot.theme <- theme()

###Size Distribution
p_0.001.a <- 
  ggplot() + 
  theme_classic() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = nonAFR.total.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.total.unmerged", fill="nonAFR.total.unmerged"), size=4, alpha=0.2) +
  coord_cartesian(xlim=c(3.99,7), ylim=c(0,3.5), expand = FALSE) +
  scale_x_continuous(breaks=seq(4,7,by = 1), labels=seq(4,7,by = 1)) +
  scale_y_continuous(breaks = seq(0,5,by=1), labels = scales::number_format(accuracy = 0.1)) +
  ggtitle('Distribution of Segment Lengths\n') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  xlab('\nSegment Length ( ln(kb) )') +
  ylab('density\n') +
  plot.theme

###################

p_0.001.b <-   
  ggplot() + 
  theme_classic() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="AFR.unshared.unmerged", fill="AFR.unshared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), color="AFR.shared.unmerged", fill="AFR.shared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), color="nonAFR.unshared.unmerged", fill="nonAFR.unshared.unmerged"), size=4, alpha=0.2) +
  geom_density(data = nonAFR.shared.unmerged , aes(x=log((end-strt)/1000), color="nonAFR.shared.unmerged", fill="nonAFR.shared.unmerged"), size=4, alpha=0.2) +
  coord_cartesian(xlim=c(3.4,7), ylim=c(0,4.1), expand = c(0)) +
  scale_x_continuous(breaks=seq(3.5,7,by = 1), labels=seq(3.5,7,by = 1)) +
  ggtitle('Distribution of Segment Lengths') +
  scale_color_brewer(type = 'qual', palette = 'Dark2') +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  xlab('Segment Length ( ln(kb) )') +
  plot.theme

###################


########
####SFS
p1 <-
  ggplot() +
  theme_classic() +
#  geom_histogram(data = nonAFR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="nonAFR.AFRshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
  geom_histogram(data = AFR.nonAFRshared.unmerged.count, aes(x=count/nrow.nonAFR, fill="AFR.nonAFRshared.unmerged.count", y=..density..), color="black", size=1, binwidth=0.00001, alpha=0.7) +
  coord_cartesian(xlim=c(0,0.001), expand = FALSE) +
#  scale_x_continuous(labels = c('0','1e-3','2e-3','3e-3','4e-3','5e-3')) +
  scale_x_continuous(labels = c('0','2.5e-4','5e-4','7.5e-4','1e-3')) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  ggtitle('Frequency of AFR Segment in Non-Africans') +
  xlab('Frequency') +
  plot.theme
############

#################  
#   ggplot() +
#   theme_bw() +
#   geom_histogram(data = nonAFR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="nonAFR.AFRshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
#   geom_histogram(data = AFR.nonAFRshared.unmerged.count, aes(x=count/nrow.nonAFR, fill="AFR.nonAFRshared.unmerged.count", y=..density..), color="black", size=1, bins=50, alpha=0.7) +
#   coord_cartesian(xlim=c(0,0.005)) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   ggtitle('Count of segments that overlap') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
#   
#   ggplot() +
#   geom_histogram(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.ASN, fill="AFR.EASshared.unmerged.count", y=..density..), alpha=0.5,bins=50) +
# #  coord_cartesian(xlim=c(0,0.005)) +
#   coord_cartesian(xlim=c(0,0.001)) +
#   ggtitle('Count of segments that overlap') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
# 
#   ggplot() +
#   geom_histogram(data = EUR.AFRshared.merged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.merged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = EAS.AFRshared.merged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.merged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = AFR.EURshared.merged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.merged.count", y=..density..), alpha=0.5,bins=50) +
#   geom_histogram(data = AFR.EASshared.merged.count, aes(x=count/nrow.ASN, fill="AFR.EASshared.merged.count", y=..density..), alpha=0.5,bins=50) +
#   coord_cartesian(xlim=c(0,0.005)) +
# #  coord_cartesian(xlim=c(0,0.001)) +
#   ggtitle('Count of segments that overlap') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
# 
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.ASN, fill="AFR.EASshared.unmerged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,0.0005)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
# 
# 
#   ggplot() +
#   geom_density(data = rbind(EUR.AFRshared.unmerged.count, EAS.AFRshared.unmerged.count), aes(x=count, fill="nonAFR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = rbind(AFR.EURshared.unmerged.count, AFR.EASshared.unmerged.count), aes(x=count, fill="AFR.nonAFRshared.unmerged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,200), ylim=c(0,0.2)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
#   
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count, fill="EUR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count, fill="EAS.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count, fill="AFR.EURshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count, fill="AFR.EASshared.unmerged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,200)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
# 
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EUR.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow.AFR, fill="EAS.AFRshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count/nrow.EUR, fill="AFR.EURshared.unmerged.count", y=..count..), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count/nrow.ASN, fill="AFR.EASshared.unmerged.count", y=..count..), alpha=0.5) +
#   coord_cartesian(xlim=c(0,0.0005)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
# 
#   ggplot() +
#   geom_density(data = EUR.AFRshared.unmerged.count, aes(x=count/nrow(EUR.AFRshared.unmerged.count), fill="EUR.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.unmerged.count, aes(x=count/nrow(EAS.AFRshared.unmerged.count), fill="EAS.AFRshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.unmerged.count, aes(x=count/nrow(AFR.EURshared.unmerged.count), fill="AFR.EURshared.unmerged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.unmerged.count, aes(x=count/nrow(AFR.EASshared.unmerged.count), fill="AFR.EASshared.unmerged.count"), alpha=0.5) +
# #  coord_cartesian(xlim=c(0,200)) +
#   ggtitle('Count of segments that overlap') +
#   theme()
#################
  
######
# p2 <- ggplot() +
#   geom_density(data = EUR.AFRshared.merged.count, aes(x=count, fill="EUR.AFRshared.merged.count"), alpha=0.5) +
#   geom_density(data = EAS.AFRshared.merged.count, aes(x=count, fill="EAS.AFRshared.merged.count"), alpha=0.5) +
#   geom_density(data = AFR.EURshared.merged.count, aes(x=count, fill="AFR.EURshared.merged.count"), alpha=0.5) +
#   geom_density(data = AFR.EASshared.merged.count, aes(x=count, fill="AFR.EASshared.merged.count"), alpha=0.5) +
#   coord_cartesian(xlim=c(0,200)) +
#   ggtitle('Count of segments that overlap a merged area') +
#   theme()
######
  
  
p3 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('Below 10%', 'Above 10%'), 
                             c(AFR.nonAFRshared.count %>% filter(count<(0.1*108)) %>% nrow()/nrow(AFR.nonAFRshared.count), 
                               AFR.nonAFRshared.count %>% filter(count>(0.1*108)) %>% nrow()/nrow(AFR.nonAFRshared.count))
                             ) %>% 
                  setnames(c('category','proportion')),
           aes(x=category, y=proportion, fill=category), stat = "identity", width=0.5 ) +
  scale_x_discrete(limits=c('Below 10%', 'Above 10%'), labels=c('Below 10%', 'Above 10%')) +
  scale_y_continuous(breaks = seq(0,1,0.2), labels= seq(0,1,0.2)) +
  coord_cartesian(ylim=c(0.045,1.05),expand = TRUE) +
  scale_fill_manual(values=c('Below 10%'='dodgerblue4','Above 10%'='orange3')) +
#  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  ggtitle('Frequency of African Segments in Africans\n') +
  xlab('\nFrequency') +
  ylab('Proportion of Total Calls\n') +
  plot.theme
  
    
####################    
# 
#   ggplot() +
#   theme_bw() +
#   geom_density(data=AFR.nonAFRunshared.count, aes(x=count, fill="AFR.nonAFR.unshared"), size=1, alpha=0.7) + 
#   geom_density(data=AFR.nonAFRshared.count, aes(x=count, fill="AFR.nonAFR.shared"),size=1, alpha=0.7) + 
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   coord_cartesian(xlim=c(0,100)) +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
#   
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count, fill="AFR.EUR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count, fill="AFR.EUR.shared"), alpha=0.75) + 
#   geom_density(data=AFR.ASNunshared.count, aes(x=count, fill="AFR.EAS.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.ASNshared.count, aes(x=count, fill="AFR.EAS.shared"), alpha=0.75) + 
#   coord_cartesian(xlim=c(0,100)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))
#   
#   ggplot() + 
#   geom_density(data=AFR.nonAFRunshared.count, aes(x=count, fill="AFR.nonAFR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.nonAFRshared.count, aes(x=count, fill="AFR.nonAFR.shared"), alpha=0.75) + 
#   coord_cartesian(xlim=c(0,200)) + 
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
#   
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count, fill="AFR.EUR.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count, fill="AFR.EUR.shared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.ASNunshared.count, aes(x=count, fill="AFR.EAS.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.ASNshared.count, aes(x=count, fill="AFR.EAS.shared", y=..count..), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,200)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()  
# 
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count/nrow(AFR.EURunshared.count), fill="AFR.EUR.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count/nrow(AFR.EURshared.count), fill="AFR.EUR.shared"), alpha=0.75) + 
#   geom_density(data=AFR.ASNunshared.count, aes(x=count/nrow(AFR.ASNunshared.count), fill="AFR.EAS.unshared"), alpha=0.75) + 
#   geom_density(data=AFR.ASNshared.count, aes(x=count/nrow(AFR.ASNshared.count), fill="AFR.EAS.shared"), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,200)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
#  
#   ggplot() +
#   geom_density(data=AFR.EURunshared.count, aes(x=count/nrow(AFR.EURunshared.count), fill="AFR.EUR.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.EURshared.count, aes(x=count/nrow(AFR.EURshared.count), fill="AFR.EUR.shared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.ASNunshared.count, aes(x=count/nrow(AFR.ASNunshared.count), fill="AFR.EAS.unshared", y=..count..), alpha=0.75) + 
#   geom_density(data=AFR.ASNshared.count, aes(x=count/nrow(AFR.ASNshared.count), fill="AFR.EAS.shared", y=..count..), alpha=0.75) + 
#  # coord_cartesian(xlim=c(0,200)) +
#   ggtitle('YRI calls, shared and unshared, SFS') +
#   theme()
####################

p4 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('ASN_EUR.total.ratio', 'ASN_EUR.minusAFR.ratio'), 
                             c(ASN_EUR.total.ratio, ASN_EUR.minusAFR.ratio)) %>% 
                  setnames(c('category','ratio')),
           aes(x=category, y=ratio, fill=category), stat = "identity", width=0.5 ) +
  geom_hline(yintercept = 1, linetype='dashed', size = 2) +
  scale_x_discrete(limits=c('ASN_EUR.total.ratio', 'ASN_EUR.minusAFR.ratio'), labels=c('Unmaksed', 'Masked')) +
  scale_y_continuous(breaks = seq(0,1.5,by = 0.2), labels=seq(0,1.5,by = 0.2)) +
  coord_cartesian(ylim=c(0.06,1.4), expand = TRUE) +
  scale_fill_manual(values=c('ASN_EUR.total.ratio'='dodgerblue4', 'ASN_EUR.minusAFR.ratio'='orange3')) +
  ggtitle('Masking African Sequence\n') +
  xlab('\nCategory') +
  ylab('Ratio of Called Sequence\n') +
  plot.theme 



p5 <- 
  ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('EUR_AFR_Shared', 'EAS_AFR_Shared'),
                             c(EUR_AFRshared.notEAS %>% mutate(len=as.numeric(end-strt)) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric(),
                               EAS_AFRshared.notEUR %>%  mutate(len=as.numeric(end-strt)) %>% summarise(sum(len)/1000000)/nonAFR_AFRshared %>% as.numeric() )
                            # c(EUR_AFRshared.notEAS %>% mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/(EUR.total.sum/1000000) %>% as.numeric(),
                            #   EAS_AFRshared.notEUR %>%  mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/(ASN.total.sum/1000000) %>% as.numeric())
                            # c(EUR_AFRshared.notEAS/EUR_AFRshared.total,
                            #   EAS_AFRshared.notEUR/EAS_AFRshared.total)
                             ) %>%
                  setnames(c('category','sum_Mb')),
           aes(x=category, y=sum_Mb, fill=category), stat = "identity", width=0.5 ) +
  scale_x_discrete(limits=c('EAS_AFR_Shared', 'EUR_AFR_Shared'), labels=c('EAS and AFR', 'EUR and AFR')) +
#  scale_y_continuous(limits = seq(0,0.1,by = 0.025), labels=seq(0,0.1,by = 0.025)) +
  coord_cartesian(ylim=c(0.0045,0.1)) +
  scale_fill_manual(values=c('EAS_AFR_Shared'='dodgerblue4', 'EUR_AFR_Shared'='orange3')) +
  ggtitle('Amount of Exclusively Shared Sequence\n') +
  # coord_cartesian(ylim=c(50,1050), expand=TRUE) +
  xlab('\nPaired Populations') +
  ylab('Proportion of Shared Sequence\n') +
  plot.theme

#############

# ggplot() +
# theme_classic() +
# geom_bar(data = data.table(c('EUR_AFR_Shared', 'EAS_AFR_Shared'), 
#                            c(EUR_AFRshared.notEAS %>% mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/nonAFR_AFRshared %>% as.numeric(), 
#                              EAS_AFRshared.notEUR %>%  mutate(len=end-strt) %>% summarise(sum(as.numeric(len))/1000000)/nonAFR_AFRshared %>% as.numeric())
#                            ) %>% 
#                 setnames(c('category','sum_Mb')),
#          aes(x=category, y=sum_Mb, fill=category), stat = "identity", width=0.5 ) +
# scale_x_discrete(limits=c('EAS_AFR_Shared', 'EUR_AFR_Shared'), labels=c('EAS and AFR', 'EUR and AFR')) +
# scale_fill_manual(values=c('EAS_AFR_Shared'='dodgerblue4', 'EUR_AFR_Shared'='orange3')) +
# coord_cartesian(ylim=c(0.0045,0.1)) +
# #  scale_fill_brewer(type = 'qual', palette = 'Dark2', direction = -1) +
# ggtitle('Amount of Exclusively Shared Sequence\n') +
# xlab('\nPaired Populations') +
# ylab('Proportion of Shared Sequence\n') +
# plot.theme


#   ggplot() + 
#   theme_bw() +
#   geom_density(data=EUR_AFRshared.notEAS, aes(x=count/nrow(EUR_AFRshared.notEAS), fill="EUR_AFRshared.notEAS", y=..count..), size=1, alpha=0.75) + 
#   geom_density(data=EAS_AFRshared.notEUR, aes(x=count/nrow(EAS_AFRshared.notEUR), fill="EAS_AFRshared.notEUR", y=..count..), size=1, alpha=0.75) + 
#   # geom_vline(aes( xintercept = median(EUR.AFRshared.count$count)+5, color="EUR.AFRshared.count"), linetype="twodash", size=2) +
#   # geom_vline(aes(xintercept = median(EAS.AFRshared.count$count)-5, color="EAS.AFRshared.count"), linetype="twodash", size=2) +
# #  coord_cartesian(xlim=c(0,500)) + 
#   ggtitle('Proportion an EUR or EAS segment is shared with YRI and not with the other nonAFR') +
#   scale_fill_brewer(type = 'qual', palette = 'Dark2') +
#   theme(plot.title=element_text(face="bold"),
#         axis.text=element_text(face="bold"),
#         axis.title=element_text(face="bold"))

###############
  
print('generate graph')
pdf("~/Desktop/SimulatedSegments_LengthAndSFS.pdf", width = 40, height = 9)
#pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0_SegLengthSFS.pdf", width = 40, height = 9)
#pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_SegLengthSFS.pdf", width = 40, height = 9)
pdf("~/Documents/Dropbox/AkeyLab/Writing/IBDadmix_102018/Figures/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0005_SegLengthSFS.pdf", width = 55, height = 9)
#grid.arrange(p1, p3, ncol=2)
#grid.arrange(p_0.001.a, p3, p4, p_0.001.b, ncol=4)
grid.arrange(p_0.001.a, p3, p4, ncol=3)
grid.arrange(p_0.001.a, p3, p4, p5, ncol=4)
dev.off()


```


############################################
############################################
############################################


```{r}
#### Empirical Data
  i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/" 
  dirpath <- i
  setwd(dirpath)
# Count of segments that overlap
  

  
e.AFR.EURshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcall.bed EURcall.bed', col.names = c('chr','strt','end', 'ID','bases','count')) %>% filter(count>=0)

e.AFR.EASshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count YRIcall.bed EAScall.bed', col.names = c('chr','strt','end', 'ID','bases','count')) %>% filter(count>=0)

e.EUR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EURcall.bed YRIcall.bed', col.names = c('chr','strt','end', 'ID','bases','count')) %>% filter(count>=0)

e.EAS.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count EAScall.bed YRIcall.bed', col.names = c('chr','strt','end', 'ID','bases','count')) %>% filter(count>=0)



#### Simulated Data
  i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0/overlaps/" 
  dirpath <- i
  setwd(dirpath)
# Count of segments that overlap
s.AFR.EURshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.50kb.bed  IntroSeg.EUR.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>=0)

s.AFR.EASshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.ASN.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>=0)

s.EUR.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.EUR.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>=0)

s.EAS.AFRshared.unmerged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>=0)


  ggplot() +
  geom_density(data = e.EUR.AFRshared.unmerged.count, aes(x=count, fill="e.EUR.AFRshared.unmerged.count"), alpha=0.5) +
  geom_density(data = e.EAS.AFRshared.unmerged.count, aes(x=count, fill="e.EAS.AFRshared.unmerged.count"), alpha=0.5) +
  #geom_density(data = s.EUR.AFRshared.unmerged.count, aes(x=count, fill="s.EUR.AFRshared.unmerged.count"), alpha=0.5) +
  #geom_density(data = s.EAS.AFRshared.unmerged.count, aes(x=count, fill="s.EAS.AFRshared.unmerged.count",), alpha=0.5) +
  geom_density(data = e.AFR.EURshared.unmerged.count, aes(x=count, fill="e.AFR.EURshared.unmerged.count"), alpha=0.5) +
  geom_density(data = e.AFR.EASshared.unmerged.count, aes(x=count, fill="e.AFR.EASshared.unmerged.count"), alpha=0.5) +
  #geom_density(data = s.AFR.EURshared.unmerged.count, aes(x=count, fill="s.AFR.EURshared.unmerged.count", y=..count..), alpha=0.5) +
  #geom_density(data = s.AFR.EASshared.unmerged.count, aes(x=count, fill="s.AFR.EASshared.unmerged.count", y=..count..), alpha=0.5) +
  coord_cartesian(xlim=c(0,200)) +
  ggtitle('Count of segments that overlap') +
  theme()

```


```{r Real Data}

  i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/Altai.2016.p_SingleArchaic" 
  dirpath <- i
  setwd(dirpath)

  
IBDmixCalls <- fread('cat ~/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/Altai2013pub.1KGP3.originalmerge.LOD4.30K.txt          ~/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/Altai2013pub.SAN.originalmerge.LOD4.30K.txt', header=TRUE)
  

ggplot() + 
  theme_bw() +
  geom_density(data=IBDmixCalls[pop %in% c('YRI', 'SAN', 'CEU')], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Segment length distribution for IBDmix Calls') +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )

ggplot() + 
  theme_bw() +
  geom_histogram(data=IBDmixCalls[pop %in% c('YRI', 'SAN', 'CEU')], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Segment length distribution for IBDmix Calls') +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )

ggplot() + 
  theme_bw() +
  geom_density(data=IBDmixCalls[anc=="AFR" & pop!="SAN"], aes(x=log((size)/1000), fill=as.factor(anc)), size=1, alpha=0.5) +
  geom_density(data=IBDmixCalls[pop=="SAN"], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  geom_density(data=IBDmixCalls[anc %in% c('SAS','EUR','EAS','AMR')], aes(x=log((size)/1000), fill=as.factor('nonAFR')), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Segment length distribution for IBDmix Calls') +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )

#################

ggplot() + 
  theme_bw() +
  geom_density(data=IBDmixCalls[anc=="AFR"], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )

ggplot() + 
  theme_bw() +
  geom_density(data=IBDmixCalls[pop %in% c('YRI', 'ESN', 'SAN', 'CEU')], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Segment length distribution for IBDmix Calls') +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )


ggplot() + 
  theme_bw() +
  geom_histogram(data=IBDmixCalls[pop!="SAN"], aes(x=(size)/1000, fill=as.factor(anc)), binwidth=5, size=1, alpha=0.7) +
  geom_histogram(data=IBDmixCalls[pop=="SAN"], aes(x=(size)/1000, fill=as.factor(anc)), binwidth=5, size=1, alpha=0.7) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(0,200)) +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )


ggplot() + 
  theme_bw() +
  geom_density(data=IBDmixCalls[anc=="AFR" & pop!="SAN"], aes(x=log((size)/1000), fill=as.factor(anc)), size=1, alpha=0.5) +
  geom_density(data=IBDmixCalls[pop=="SAN"], aes(x=log((size)/1000), fill=as.factor(pop)), size=1, alpha=0.5) +
  geom_density(data=IBDmixCalls[anc %in% c('SAS','EUR','EAS','AMR')], aes(x=log((size)/1000), fill=as.factor('nonAFR')), size=1, alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2') +
  coord_cartesian(xlim=c(2,7)) +
  ggtitle('Segment length distribution for IBDmix Calls') +
    theme(plot.title=element_text(face="bold"),
        axis.text=element_text(face="bold"),
        axis.title=element_text(face="bold")
        )
#################


  
AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID' ,'pop','anc','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcalls.bed EUR_EAS_SAS_AMR_calls.bed.merged', col.names = c('chr','strt','end', 'ID', 'pop','anc','bases','indicator')) %>% filter(indicator==0)
  
  



nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_call.50kb.bed YRIcall.50kb.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==1)

nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EUR_EAS_SAS_AMR_call.50kb.bed YRIcall.50kb.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==0)


  
##### 2-way
AFR.EURshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcall.bed EURcall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)

AFR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcall.bed EAScall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)

EUR.AFRshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcall.bed YRIcall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)

EAS.AFRshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EAScall.bed YRIcall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)

EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcall.bed EAScall.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==1)

EAS.EURshared.merged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EAScall.bed EURcall.bed.merged', col.names = c('chr','strt','end','ID','bases','indicator')) %>% filter(indicator==1)

AFR.EUR_EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcall.bed EUR_EAScall.bed.merged', col.names = c('chr','strt','end', 'ID','bases','indicator')) %>% filter(indicator==1)


##### 3-way
EUR.EAS.AFRshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcall.bed EAScall.bed.merged | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - YRIcall.bed.merged ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)

EAS.EUR.AFRshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EAScall.bed EURcall.bed.merged | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - YRIcall.bed.merged ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)

AFR.EUR.EASshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcall.bed EURcall.bed.merged | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - EAScall.bed.merged ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)


EUR.EAS.AFRshared <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EURcall.bed EAScall.bed | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - YRIcall.bed ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)

EAS.EUR.AFRshared <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator EAScall.bed EURcall.bed | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - YRIcall.bed ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)

AFR.EUR.EASshared <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator YRIcall.bed EURcall.bed | bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator - EAScall.bed ', col.names = c('chr','strt','end','ID','bases1','indicator1', 'bases2','indicator2')) %>% filter(indicator1==1 & indicator2==1)
```


```{r Simulation Data}

  i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0/overlaps/" 
  dirpath <- i
  setwd(dirpath)


AFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

AFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.50kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)

####
nonAFR.shared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==1)

nonAFR.unshared.unmerged <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged', col.names = c('chr','strt','end','bases','indicator')) %>% filter(indicator==0)


####
AFR.EURshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged  IntroSeg.EUR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)

AFR.EASshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.AFR.D4E0.002.ALL.30kb.bed.merged IntroSeg.ASN.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)

EUR.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.EUR.D4E0.002.ALL.30kb.bed.merged IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)

EAS.AFRshared.merged.count <- fread('bedmap --ec --delim "\t" --echo --bases --fraction-map 0.001 --count IntroSeg.ASN.D4E0.002.ALL.30kb.bed.merged IntroSeg.AFR.D4E0.002.ALL.30kb.bed', col.names = c('chr','strt','end','bases','count')) %>% filter(count>0)



####
AFR.nonAFRunshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0)

AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --count - ",
                                 col.names = c('chr','strt','end','count')) %>% filter(count>0)


# AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==0) print $1,$2,$3 }' | bedtools merge -i - -c 1 -o count",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)
# 
# AFR.nonAFRshared.count <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.AFR.D4E0.002.ALL.30kb.bed IntroSeg.EUR_ASN.D4E0.002.ALL.30kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedtools merge -i - -c 1 -o count",
#                                   col.names = c('chr','strt','end','count')) %>% filter(count>0)

ggplot() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
  geom_density(data = AFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.shared.unmerged"), alpha=0.5) +
  geom_density(data = nonAFR.shared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.shared.unmerged"), alpha=0.5) +
  geom_density(data = nonAFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="nonAFR.unshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('p_0.001') +
  theme()


p6 <-
ggplot() +
  geom_density(data = EUR.AFRshared.merged.count, aes(x=count, fill="EUR.AFRshared.merged.count"), alpha=0.5) +
  geom_density(data = EAS.AFRshared.merged.count, aes(x=count, fill="EAS.AFRshared.merged.count"), alpha=0.5) +
  geom_density(data = AFR.EURshared.merged.count, aes(x=count, fill="AFR.EURshared.merged.count"), alpha=0.5) +
  geom_density(data = AFR.EASshared.merged.count, aes(x=count, fill="AFR.EASshared.merged.count"), alpha=0.5) +
  coord_cartesian(xlim=c(0,200)) +
  ggtitle('p_0.001') +
  theme()

p5 <- 
  ggplot() + 
  geom_density(data=AFR.nonAFRunshared.count, aes(x=count, fill="AFR.nonAFR.unshared"), alpha=0.75) + 
  geom_density(data=AFR.nonAFRshared.count, aes(x=count, fill="AFR.nonAFR.shared"), alpha=0.75) + 
  coord_cartesian(xlim=c(0,200)) + 
  ggtitle('YRI calls, shared and unshared, SFS') +
  theme()


```


``` {r}
ggplot() +
  geom_density(data = AFR.EURshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EURshared.unmerged"), alpha=0.5) +
  geom_density(data = AFR.EUR_EASshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EUR_EASshared.unmerged"), alpha=0.5) +
  geom_density(data = AFR.EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EUR.EASshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('p_0.001') +
  theme()


ggplot() +
  geom_density(data = EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.EASshared.unmerged"), alpha=0.5) +
  geom_density(data = EAS.EURshared.merged, aes(x=log((end-strt)/1000), fill="EAS.EURshared.merged"), alpha=0.5) +
  geom_density(data = EUR.AFRshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.AFRshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('p_0.001') +
  theme()


ggplot() +
  geom_density(data = AFR.unshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.unshared.unmerged"), alpha=0.5) +
  geom_density(data = AFR.EUR.EASshared.unmerged, aes(x=log((end-strt)/1000), fill="AFR.EUR.EASshared.unmerged"), alpha=0.5) +
  geom_density(data = EUR.EAS.AFRshared.unmerged, aes(x=log((end-strt)/1000), fill="EUR.EAS.AFRshared.unmerged"), alpha=0.5) +
  geom_density(data = EAS.EUR.AFRshared.unmerged, aes(x=log((end-strt)/1000), fill="EAS.EUR.AFRshared.unmerged"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('p_0.001') +
  theme()


ggplot() +
  geom_density(data = EUR.EAS.AFRshared, aes(x=log((end-strt)/1000), fill="EUR.EAS.AFRshared"), alpha=0.5) +
  geom_density(data = EAS.EUR.AFRshared, aes(x=log((end-strt)/1000), fill="EAS.EUR.AFRshared"), alpha=0.5) +
  geom_density(data = AFR.EUR.EASshared, aes(x=log((end-strt)/1000), fill="AFR.EUR.EASshared"), alpha=0.5) +
#  geom_density(data = rbind(EUR.EAS.AFRshared, AFR.EUR.EASshared), aes(x=log((end-strt)/1000), fill="AFR_EUR.EASshared"), alpha=0.5) +
  coord_cartesian(xlim=c(0,7)) +
  ggtitle('p_0.001') +
  theme()



```




