---
title: "Untitled"
author: "Aaron Wolf"
date: "8/26/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(RColorBrewer)
```


```{r}

i <-  "/Users/abwolf/DATALab/NeanderthalSeq/IBDmix/Altai.2013.p_SingleArchaic.final_callset/" 
dirpath <- i
setwd(dirpath)



print('Measure how frequent an EUR or EAS segment is in its respective population if it is shared with YRI, but not shared with the other nonAFR pop ; does this explain why YRI-masking has a greater effect on EUR than EAS even though similar rates of overlap?')


EUR_AFRshared.notEAS <- fread("bedmap --ec --delim '\t' --echo --bases --bp-ovr 1 --indicator EURcalls.bed YRIcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - EAScalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% mutate(len = end-strt)

EAS_AFRshared.notEUR <- fread("bedmap --ec --delim '\t' --echo --bases --bp-ovr 1 --indicator EAScalls.bed YRIcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - EURcalls.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% mutate(len = end-strt)

nonAFR.total.unmerged <- fread('EUR_EAS_SAS_AMR_calls.bed', col.names = c('chr','strt','end','ID', 'pop','anc')) %>% mutate(len = end-strt)
```


```{r}

 # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/preOOA/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0_pOOA_0.05/IBDmixCalls/"
 # i <-  "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/n1_0.05/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005/IBDmixCalls/"
 # i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_preOOA_0.1/IBDmixCalls/"
i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.00005_preOOA_0.05/IBDmixCalls/"
# i <- "/Users/abwolf/DATALab/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Sriram/mixture_model/n1_0.05_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.000025_preOOA_0.1/IBDmixCalls/"

  dirpath <- i
  setwd(dirpath)
  
EUR_AFRshared.notEAS <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.EUR.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - IntroSeg.ASN.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% mutate(len = end-strt)

EAS_AFRshared.notEUR <- fread("bedmap --ec --delim '\t' --echo --bases --fraction-map 0.001 --indicator IntroSeg.ASN.D4E0.002.ALL.50kb.bed IntroSeg.AFR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} {if ($NF==1) print $1,$2,$3 }' | bedmap --ec --delim '\t' --echo --fraction-map 0.001 --indicator - IntroSeg.EUR.D4E0.002.ALL.50kb.bed.merged | awk 'BEGIN {OFS=\"\t\"} { if($NF==0) print $1,$2,$3}' | bedmap --ec --delim '\t' --echo --count - ",
                                  col.names = c('chr','strt','end','count')) %>% filter(count>0) %>% mutate(len = end-strt)
  
nonAFR.total.unmerged <- fread('IntroSeg.EUR_ASN.D4E0.002.ALL.50kb.bed', col.names = c('chr','strt','end')) %>% mutate(len = end-strt)


```





```{r}

quantile(nonAFR.total.unmerged$len, c(0.01,0.1))

median(EUR_AFRshared.notEAS$len)
median(EAS_AFRshared.notEUR$len)

quantile(EUR_AFRshared.notEAS$len, c(0.01,0.1))
quantile(EAS_AFRshared.notEUR$len, c(0.01,0.1))


```



```{r}
plot.theme <-theme(
        #legend.position="none"m
        legend.text=element_text(size=10),
        #panel.grid.major=element_line(color="black"),
        panel.grid=element_blank(),
        axis.line.x=element_line(color="black", size=2),
        axis.line.y=element_line(color="black",size=2),
        plot.title=element_text(face="bold", color="black", size=42, hjust = 0.5, family = "Helvetica"),
        axis.text=element_text(face="bold", color="black", size=42, family = "Helvetica"),
        axis.title=element_text(face="bold", color="black", size=42, family = "Helvetica")
        )
```


```{r}

ggplot() + 
  theme_classic() +
  geom_density(data=EUR_AFRshared.notEAS, aes(x=log(len), fill='EUR_AFR_shared', color='EUR_AFR_shared'), alpha=0.5) +
  geom_density(data=EAS_AFRshared.notEUR, aes(x=log(len), fill='EAS_AFR_shared', color='EAS_AFR_shared'), alpha=0.5) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2', direction = -1) +
  theme()


ggplot() +
  theme_classic() +
  geom_bar(data = data.table(c('EUR_AFR_Shared', 'EAS_AFR_Shared'), 
                             c(EUR_AFRshared.notEAS %>% filter(len <= quantile(EUR_AFRshared.notEAS$len, c(0.01))[[1]] ) %>% summarise(sum(len)/1000000) %>% as.numeric(), 
                               EAS_AFRshared.notEUR %>% filter(len <= quantile(EAS_AFRshared.notEUR$len, c(0.01))[[1]] ) %>% summarise(sum(len)/1000000) %>% as.numeric() )
                             ) %>% 
                  setnames(c('category','sum_Mb')),
           aes(x=category, y=sum_Mb, fill=category), stat = "identity", width=0.5 ) +
  scale_x_discrete(limits=c('EAS_AFR_Shared', 'EUR_AFR_Shared'), labels=c('EAS : AFR', 'EUR : AFR')) +
#  scale_y_continuous(breaks = seq(0,12,2), labels= seq(0,12,2)) +
#  coord_cartesian(ylim=c(0,13)) +
  scale_fill_brewer(type = 'qual', palette = 'Dark2', direction = -1) +
  ggtitle('Amount of Exclusively Shared Sequence\n') +
#  coord_cartesian(ylim=c(50,1050), expand=TRUE) +
  xlab('\nPaired Populations') +
  ylab('Shared Sequence (Mb)\n') +
  plot.theme

grid.arrange(a,b,c, ncol=3)



```

